# -*- coding: utf-8 -*-
"""公文RAG_9種.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V_1m7MwK8ti7nBhkPNj7QwaR6hjj5rUG
"""

from google.colab import drive
drive.mount('/content/drive')

!ls /content/drive/MyDrive/

!cp -r /content/drive/MyDrive/rag_docs /content/

!pip install -U \
    langchain langchain-community langchain-core langchain-text-splitters \
    chromadb \
    sentence-transformers \
    transformers \
    huggingface_hub \
    aisuite \
    gradio

import os

from langchain_community.document_loaders import TextLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.vectorstores import Chroma

import aisuite as ai
import gradio as gr

try:
    from google.colab import userdata
    api_key = userdata.get('Groq')
    if api_key:
        os.environ["GROQ_API_KEY"] = api_key
except Exception:
    pass

# 建立 aisuite Client（Groq）
client = ai.Client()
MODEL_NAME = "groq:llama-3.3-70b-versatile"

"""##掃描向量文件"""

BASE_DIR = "rag_docs"

subdirs = ["cases", "cocepts", "laws", "structure"]  # 照你現在的命名

documents = []

for sub in subdirs:
    folder = os.path.join(BASE_DIR, sub)
    if not os.path.isdir(folder):
        print(f"⚠️ 資料夾不存在，略過：{folder}")
        continue

    for fname in os.listdir(folder):
        if not fname.endswith(".txt"):
            continue
        path = os.path.join(folder, fname)
        loader = TextLoader(path, encoding="utf-8")
        docs = loader.load()
        # 補 metadata：之後可以用 filter 篩某類資料
        for d in docs:
            d.metadata["category"] = sub
            d.metadata["filename"] = fname
        documents.extend(docs)

len(documents)

"""##切 chunk + 建立Chroma"""

text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=800,
    chunk_overlap=200
)
split_docs = text_splitter.split_documents(documents)
print("Chunks 數量：", len(split_docs))

embedding_model = HuggingFaceEmbeddings(
    model_name="intfloat/multilingual-e5-large"
)

CHROMA_DIR = "rag_chroma"

vectordb = Chroma.from_documents(
    documents=split_docs,
    embedding=embedding_model,
    persist_directory=CHROMA_DIR,
)

vectordb.persist()
print("✅ Chroma 建好並已 persist 在", CHROMA_DIR)

from langchain_community.vectorstores import Chroma
from langchain_community.embeddings import HuggingFaceEmbeddings

embedding_model = HuggingFaceEmbeddings(
    model_name="intfloat/multilingual-e5-large"
)

vectordb = Chroma(
    embedding_function=embedding_model,
    persist_directory="rag_chroma"
)

DOC_TYPE_TO_STRUCTURE = {
    "扣押命令": "扣押命令_structure.txt",
    "保單查詢": "保單查詢_structure.txt",
    "保單註記": "保單註記_structure.txt",
    "保單查詢＋註記": "保單查詢＋註記_structure.txt",
    "收取令": "收取令_structure.txt",
    "撤銷令": "撤銷令_structure.txt",
    "收取＋撤銷": "收取＋撤銷_structure.txt",
    "通知函": "通知函_structure.txt",
    "公職查詢": "公職查詢_structure.txt",
}

STRUCTURE_DIR = os.path.join(BASE_DIR, "structure")

def load_structure_text(doc_type: str) -> str:
    fname = DOC_TYPE_TO_STRUCTURE.get(doc_type)
    if not fname:
        raise ValueError(f"未知的 doc_type: {doc_type}")
    path = os.path.join(STRUCTURE_DIR, fname)
    with open(path, "r", encoding="utf-8") as f:
        return f.read()

def retrieve_context(query: str, k: int = 8, category: str | None = None) -> str:
    if category:
        docs = vectordb.similarity_search(
            query,
            k=k,
            filter={"category": category}
        )
    else:
        docs = vectordb.similarity_search(query, k=k)

    return "\n\n".join(
        f"[{d.metadata.get('category','')}/{d.metadata.get('filename','')}] {d.page_content}"
        for d in docs
    )

api_key = userdata.get("Groq")
os.environ["GROQ_API_KEY"] = api_key

client = ai.Client()
MODEL_NAME = "groq:openai/gpt-oss-20b"
#qwen/qwen3-32b
#llama-3.3-70b-versatile
#llama-3.1-8b-instant
#openai/gpt-oss-20b

SYSTEM_PROMPT = """
你是一個專門處理台灣法院與機關公文的「欄位擷取助手」。
你的任務是：
1. 讀懂公文。
2. 結合提供的法條、概念、案例說明（RAG context）。
3. 嚴格按照「輸出格式要求」產出結果。
4. 不要多加任何解釋、前言或後記，只輸出擷取結果本身。

請用台灣習慣的繁體中文。
""".strip()


def extract_with_rag(raw_doc: str, doc_type: str, k: int = 8) -> str:
    # 1. 讀取該類型的 structure 說明＋格式
    structure_text = load_structure_text(doc_type)

    # 2. 讓 RAG 幫忙找相關 laws / concepts / cases
    #    這裡用整份公文當 query，比較穩
    rag_context = retrieve_context(
        query=raw_doc,
        k=k,
        category=None,  # 想只用 laws 可改 "laws"，或只用 "cases"
    )

    # 3. 組 user prompt
    user_prompt = f"""
公文類型：{doc_type}

【公文原文】：
{raw_doc}

【相關知識（法律、概念、案例等，僅供你參考推理）】：
{rag_context}

【輸出格式與欄位說明】：
{structure_text}

請你依照「輸出格式要求」，對這份公文做欄位擷取與整理：
- 僅輸出整理好的結果本身。
- 若某欄位原文中沒有明確資訊，請填「無明確記載」或依結構檔的指示處理。
    """.strip()

    response = client.chat.completions.create(
        model=MODEL_NAME,
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": user_prompt},
        ],
    )
    return response.choices[0].message.content

pip install groq

import gradio as gr

DOC_TYPES = list(DOC_TYPE_TO_STRUCTURE.keys())  # Dropdown 用

def ui_extract(doc_text, doc_type):
    if not doc_text.strip():
        return "請先貼上完整公文。"
    return extract_with_rag(doc_text, doc_type)

with gr.Blocks() as demo:
    gr.Markdown("# 📄 九類公文擷取 RAG 測試版")

    with gr.Row():
        doc_type = gr.Dropdown(
            choices=DOC_TYPES,
            value="扣押命令",
            label="公文類型"
        )
    doc_input = gr.Textbox(
        lines=18,
        label="請貼上完整公文原文",
        placeholder="例如：\n臺灣○○地方法院民事執行處 執行命令..."
    )
    output = gr.Textbox(
        lines=20,
        label="擷取結果"
    )

    btn = gr.Button("開始擷取")
    btn.click(ui_extract, inputs=[doc_input, doc_type], outputs=output)

demo.launch(debug=True)

